### ISSUE TITLE
Automated Issue from Flow Launcher 

### ISSUE THREAD

**Issue by BrodyMcLemore** [Garulf/spell-checker#3]
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\OKsho\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: 
Date: 01/05/2023 14:51:55
Exception:
Spell Checker Exception: 
Websites: https://github.com/Garulf/spell-checker
Author: Garulf
Version: 0.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\run.py", line 9, in <module>
    from plugin.main import SpellChecker
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\plugin\main.py", line 6, in <module>
    from textblob import Word, TextBlob
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\textblob\__init__.py", line 2, in <module>
    from .blob import TextBlob, Word, Sentence, Blobber, WordList
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\textblob\blob.py", line 29, in <module>
    import nltk
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\nltk\__init__.py", line 137, in <module>
    from nltk.text import *
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\nltk\text.py", line 29, in <module>
    from nltk.tokenize import sent_tokenize
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\nltk\tokenize\__init__.py", line 65, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\nltk\tokenize\casual.py", line 49, in <module>
    import regex  # https://github.com/nltk/nltk/issues/2409
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\run.py", line 9, in <module>
    from plugin.main import SpellChecker
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\plugin\main.py", line 6, in <module>
    from textblob import Word, TextBlob
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\textblob\__init__.py", line 2, in <module>
    from .blob import TextBlob, Word, Sentence, Blobber, WordList
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\textblob\blob.py", line 29, in <module>
    import nltk
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\nltk\__init__.py", line 137, in <module>
    from nltk.text import *
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\nltk\text.py", line 29, in <module>
    from nltk.tokenize import sent_tokenize
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\nltk\tokenize\__init__.py", line 65, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\nltk\tokenize\casual.py", line 49, in <module>
    import regex  # https://github.com/nltk/nltk/issues/2409
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\OKsho\AppData\Roaming\FlowLauncher\Plugins\Spell Checker-0.1.0\lib\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 292
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 307
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 785
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by BrodyMcLemore** [comment]
Log File. 
[2023-01-05.txt](https://github.com/Garulf/spell-checker/files/10355626/2023-01-05.txt)

**Comment by Garulf** [comment]
This plugin has been removed from Flows plugin store as it's required libraries depended on some binary files to work. I have a workaround but have not implemented it yet due to time constraints. 

In the mean time you should be able to get this plugin to run using Python 3.8.

**Comment by BrodyMcLemore** [comment]
Ok, I'll point my flow python path to 3.8 instead of 3.10 and see if that fixes it.

**Comment by BrodyMcLemore** [comment]
Pointing to python 3.8 instead of 3.10 solved the issue.
